export const FETCH_MAP_DATA = 'FETCH_MAP_DATA';
export const FETCH_MAP_DATA_SUCCESS = 'FETCH_MAP_DATA_SUCCESS';
export const FETCH_MAP_DATA_ERROR = 'FETCH_MAP_DATA_ERROR';

export const CALCULATE_DATA = 'CALCULATE_DATA';
export const CALCULATE_DATA_SUCCESS = 'CALCULATE_DATA_SUCCESS';
export const CALCULATE_DATA_ERROR = 'CALCULATE_DATA_ERROR';
export const CALCULATE_DATA_IS_EQUAL = 'CALCULATE_DATA_IS_EQUAL';